apiVersion: v1
kind: Secret
metadata:
    name: immich-secrets
    namespace: immich
type: Opaque
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:fssMp29J,iv:8cLCnQxH1ytpgSW6oiyciN7nHOttzQII2fdhxQFRlso=,tag:2pBjzLjCyDclx8OqDNruLA==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:WjGarwZO,iv:8mPF+vKwmUKFlGD6L78nSIhQSJUcL6Eufx6NzbW7jBY=,tag:ZDganqn/5+c/DXow9TZSTQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:QYnFFfgmyQMK1yEq7/kG/6KpJ0XrCo01TBOk3r+v2qw=,iv:uMyllg1NeM17ISkc9+qmB+yBxxSe7AYwCKAO2CRbCmU=,tag:5cDx7LWdOU010mVhcLvCMw==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:2eGQGMeELoJrhqhhMTNxdkLb+o+ruJfp6ths00T3,iv:NALUxNCujtKCO1V78hrWZbVG5+jHxsLDrRbWlJou/dU=,tag:ulcRo7CTHSqMMP3GVKMOQg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UzNOei8wY1dLSWFyMUE4
            cXVZRDd0aDJMay8ycWU5RXI1L2ZSTy9BTVVJCmlqWFdMQVFyM25jczB1VkJKM0d3
            R2FrdlZ2MUp5MGVLUmdHK3ZBc0hrL28KLS0tIC80ZE8wZHVHQWh2cGx1TDc5emxx
            SHArQ3FjSm4vRDR1MWlYVFJmblc3Mm8KDVgvjBDlPXDdu7FCfJonTafycLMjKcFV
            zJmwvlvNj54CPZGUF+cBkWsuwkbYlqOy6nPTXZQZRAu/VlPYwB853g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1srsysv2m9nq49zdfk0y7twm80pyg72qnm6hql5y6er38mg3q3c0qn4ljtw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T11:43:46Z"
    mac: ENC[AES256_GCM,data:DGC56BChYkEpruLRZCTMXB1dH9sq5fRaMVorlVFRCyBr75mytTHYSUZnjG0Rn2CSl8/9fYkL6J9JllucWs0qO0QlEIkiNPjp7LJXknLU8bMRajEDndjxgeizw2kqmMO4trOn3F3uTO5dm4AVsYXyShfUuwIQ1wXuguNdSrI422o=,iv:KE9grmkL6+anAXQY+1O4OKT0EjCme0buuGYDRePi1lk=,tag:x9Z2np1RexaC5FPsrNW9rg==,type:str]
    version: 3.13.3
