apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secrets
    namespace: home-assistant
type: Opaque
stringData:
    secrets.yaml: ENC[AES256_GCM,data:0gkvm1lqWc1haaauEjAKxD3r+eiRvxInG7BI2UI8ieP88AsUaxHBChcShbo7egxK1N9iNmMQIEfUuj80vZjC7h0b+J8xSjaRfhGFd2cV5uKINMQtxX3CWsjY9UXaNwbblkaQ6MMdJAjHrvqk9IA8rXe2AKjEIGG38g==,iv:HiTtnxGKbvng0x1BjmJW1CCJwCJB7mYcoOMXsZJ9VvQ=,tag:FAURQpm8xQ0Mn9y7OlNAfA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VzRyNTZRWStHbXA2K1F1
            TVdUVjByUmxxU3ZCWS9ta0Y0OFNMcWZwTlZjCk9mVmJ1VGZGZEtybG4yVWVGaUEv
            NFBTTGtFa3ZHOUhNQkNVS2xXTWxzVG8KLS0tIEw2eVFPZ2lFSmZ5c3JFeGtxMStL
            b1Z0OFN5bTVWQS9JRHJ6b2puTzJvMW8KO6Bx78oZ0VSYUm/pivj9HC7utfBfCCjZ
            DlgxMA1UaGA+6h+PRptDg/VGwbO9huTH64TgDEp3sVCo6H17mPs9OA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1srsysv2m9nq49zdfk0y7twm80pyg72qnm6hql5y6er38mg3q3c0qn4ljtw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T16:56:50Z"
    mac: ENC[AES256_GCM,data:5+2DeinVYikkLgTwSd+MtOgrkDNcrYBcjRALAq9IY+FhCH7SoYPgxHy2BbpYMG9qhGjx8oD7i5Gu1W0vEZvMUpww/S//bc7q3OeSVstVZiHyImE3mBV2/4r6jw3825a/oqYxAxz8RQ8udUZ6askxGNQQ5NuyBmLvhuP/NCbojAI=,iv:VbGuInXqkMupymnkPouOBMlupJX1GUP23jJbuXUpwEY=,tag:tQQLK7ggU2fUvyh4vCO8ow==,type:str]
    version: 3.13.1
