clusterName: dbnet
talosVersion: v1.13.5
kubernetesVersion: v1.36.2
endpoint: https://10.0.0.41:6443

patches:
  - |-
    cluster:
      extraManifests:
        - https://github.com/fluxcd/flux2/releases/latest/download/install.yaml

  - |-
    machine:
      network:
        nameservers:
          - 10.0.0.5
          - 10.0.0.22

controlPlane:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/qemu-guest-agent

worker:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/util-linux-tools
          - siderolabs/nvme-cli
          - siderolabs/nfs-utils
          - siderolabs/qemu-guest-agent

nodes:
  - hostname: talos-cp-1
    ipAddress: 10.0.0.41
    installDisk: /dev/sda
    controlPlane: true
    networkInterfaces:
      - interface: eth0
        dhcp: false
        addresses: [10.0.0.41/24]
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.0.1

  - hostname: talos-wk-1
    ipAddress: 10.0.0.42
    installDisk: /dev/sda
    controlPlane: false
    networkInterfaces:
      - interface: eth0
        dhcp: false
        addresses: [10.0.0.42/24]
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.0.1
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/nonfree-kmod-nvidia-lts
            - siderolabs/nvidia-container-toolkit-lts
    patches:
      - |-
        machine:
          kernel:
            modules:
              - name: nvidia
              - name: nvidia_uvm
              - name: nvidia_drm
              - name: nvidia_modeset

  - hostname: talos-wk-2
    ipAddress: 10.0.0.43
    installDisk: /dev/sda
    controlPlane: false
    networkInterfaces:
      - interface: eth0
        dhcp: false
        addresses: [10.0.0.43/24]
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.0.1