apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: arr
spec:
  selector:
    app: qbittorrent
  ports:
    - name: webui
      port: 8080
      targetPort: webui
    - name: torrent-tcp
      port: 6881
      targetPort: torrent-tcp
      protocol: TCP
    - name: torrent-udp
      port: 6881
      targetPort: torrent-udp
      protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: arr
spec:
  selector:
    app: sonarr
  ports:
    - name: http
      port: 8989
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: arr
spec:
  selector:
    app: radarr
  ports:
    - name: http
      port: 7878
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: arr
spec:
  selector:
    app: prowlarr
  ports:
    - name: http
      port: 9696
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
  namespace: arr
spec:
  selector:
    app: bazarr
  ports:
    - name: http
      port: 6767
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  namespace: arr
spec:
  selector:
    app: flaresolverr
  ports:
    - name: http
      port: 8191
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: arr
spec:
  selector:
    app: jellyfin
  ports:
    - name: http
      port: 8096
      targetPort: http
