http:
  routers:
    beszel:
      rule: "Host(`beszel.dbnet.work`)"
      entryPoints: ["websecure"]
      tls: {}
      service: beszel-svc
  services:
    beszel-svc:
      loadBalancer:
        servers:
          - url: "http://10.0.0.5:8090"
        passHostHeader: true
