- name: Create mediapool as RAIDZ1
  community.general.zpool:
    name: "{{ zfs_pool_name }}"
    state: present
    mountpoint: "{{ zfs_mountpoint }}"
    pool_properties:
      ashift: "{{ zfs_ashift }}"
    filesystem_properties:
      compression: "{{ zfs_compression }}"
    vdevs:
      - type: raidz1
        disks: "{{ zfs_disks }}"

- name: Register mediapool in Proxmox
  community.proxmox.proxmox_storage:
    name: "{{ proxmox_storage_id }}"
    state: present
    type: zfspool
    nodes: "{{ proxmox_storage_nodes }}"
    content:
      - images
    zfspool_options:
      pool: "{{ zfs_pool_name }}"
      sparse: true
  delegate_to: localhost
  vars:
    ansible_become: false
