creation_rules:
  - path_regex: talos/talsecret\.sops\.yaml
    age: age1srsysv2m9nq49zdfk0y7twm80pyg72qnm6hql5y6er38mg3q3c0qn4ljtw

  - path_regex: infra/.*/secret.*\.yaml$
    encrypted_regex: "^(data|stringData)$"
    age: age1srsysv2m9nq49zdfk0y7twm80pyg72qnm6hql5y6er38mg3q3c0qn4ljtw
