default_config:

frontend:
#  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.20
    - 10.0.0.41
    - 10.0.0.42
    - 10.0.0.43

#smartir:

climate:
  - platform: smartir
    name: AC
    unique_id: living_room_ac
    device_code: 1390
    controller_data:
      controller_type: Broadlink
      remote_entity: remote.universal_remote
      delay_secs: 0.5
      num_repeats: 3