apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opencloud

resources:
  - namespace.yaml
  - storage.yaml
  - secret.yaml
  - ldap.yaml
  - opencloud-config.yaml
  - opencloud.yaml
  - proxy.yaml
  - service.yaml

configMapGenerator:
  - name: opencloud-ldap-files
    files:
      - 10_opencloud_schema.ldif
      - 10_base.ldif
      - docker-entrypoint-override.sh
    options:
      disableNameSuffixHash: true

  - name: opencloud-csp
    files:
      - csp.yaml
    options:
      disableNameSuffixHash: true
