# IMPORTANT: Encrypt this file with SOPS.
apiVersion: v1
kind: Secret
metadata:
    name: opencloud-ldap
    namespace: opencloud
type: Opaque
stringData:
    LDAP_BIND_PASSWORD: ENC[AES256_GCM,data:FNtEqubJ1pgLLVdNoHhv4PqvtHx36htf1GIN8daRCZs=,iv:8A82Z2fRwjqBRIJ3adEuRrMKD2jwyNVBATjga/+znuo=,tag:U0cHNjo/m4dYxSt4aL1EPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdnovZ0NoQ3RPUU9mWEFD
            U3M5QVNSTy91dkNobU83OXpnTU1aTGhveTBNCjdkQVVsSHlHd3JhSXNXeXdCT05u
            TE9kR0RSdVErenF0SkVId0p6VTVsWDQKLS0tIHVEdEVlNXBWa2ZqLytHL3dGRHVu
            WjB5eDU3M3RpcWpvbVFKdDd1dzNBU2sKEVaYYDLLQDlQzrWcpqj2droC1Itf3ncD
            VzEPmX9aJ7exsZ2FQzAADJNdPqNwH2li/am0kXWuk+Tao4B/SfdHWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1srsysv2m9nq49zdfk0y7twm80pyg72qnm6hql5y6er38mg3q3c0qn4ljtw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T16:08:49Z"
    mac: ENC[AES256_GCM,data:T3RLvu8Pg2zGHX+B5qKD0ZRYVz+JeIjHVXjCB2UM6QfNBn0X2AKVikfA1tBfhVp/337iPGWcp1I0oQ3nLIgw/CyaQlYIyHHH3uHvjk1ssYzeWQ4pxzUY0Tu6PPsN3/UDW2olNHyzO3c8Db+iOSzqzoovWeqW+P4aIEo/mEX8sKg=,iv:mPzXfeLYGPGSQ1UiVSmm/fZ1xt+7u4BH4O8cGHbbd7I=,tag:uFztTPziS5rmjwr5G8UorQ==,type:str]
    version: 3.13.3
