apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencloud-config
  namespace: opencloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-data
  namespace: opencloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-certs
  namespace: opencloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: opencloud-nfs
spec:
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
  nfs:
    server: 10.0.0.14
    path: /srv/nfs/cloud

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencloud-data
  namespace: opencloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: opencloud-nfs
  resources:
    requests:
      storage: 300Gi
